language: java
jdk:
- oraclejdk8
script: env && ./mvnw package -B
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: esuez@pivotal.io
  password:
    secure: iDY42kJSN8gttCwUdS7YvID8Wf+WsJehVLNDDShRzxixkNrj01Oq1FfmTKcd1Wlxf7D0FVd2mHGWYNadVtOMz5amHfFWTbw+YMQu1l1OmFUsFxKrTRAyUgHGFxpXgFRUw4ox7fdCJPEDRBVX3qiCQbxImLqtZ2fagmzxNTgCcMqNyK42hDNHIRvdp7q4/q5VeHTitB0/35fyrLG+XcrEjkFhW0VwcgWVanv4SBrAwdYxt9aL59F63//7q2wAKkBrfsxAXLXvbbPHJwBxOln6lj+ujczGSPBp9DrRF0uVi2MpaaCYzKGAi8LJCEHXiK1UXEwI4ARoV1WKsT0fjRZQw/d/+xZBbOTwY7nyIB4s4LZ21vI5pVetux1kVSZY3XThJnkpGGkUPBZWOIA7qK1wA5LK53ViRDXi97ONTLfdqek9CmugaA4jNZVlkclw37qera/L2u5P5PUPuGvYJWz8giUp0yGKsrwlQYNQoKbP332bGH3v0/1CZ/9uRHbvL+t4cD5fhRQxfB8fN7pCpUnAubjL14S9ORcuvvw/1utGmFxbc5xrOmKeS311/dnPQ7xX+G1BIKcIFijbV9rZGXpmozaUNh5tpbK9spk8VNhAUG4hD2tgE5eBk8zELL/nAbP1YY4m0MGIlfi3++1CCgiMWPrpUZwp+sWZmFBYqqHNprY=
  organization: eitan-org
  space: eitan-space
  on:
    repo: eitansuez/articulate
