language: java
jdk:
- oraclejdk8
script: env && ./mvnw package -B
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  organization: eitan-org
  space: eitan-space
  username: esuez@pivotal.io
  password:
    secure: PUjyM6+TCpnBj2eLKAvbcTt4blGJ1B2VqKeRRTOwfjbu8HrxEi2sDlCAIFs9nibeRzFDIyT0Lw7o4LLH34Ma1n7U2BrbKQkNzhCBQE/sjRP0WedyGiW+kK73QMCejfKC3hCAsNnv7dMWNumFQd4LJD4h+NCq5ialTqvnfN34Bk3OjYy/cEJWgXcNk/RUhpPtpyuiv0m38AA1lmbvlYUzfTTrDWfex3/TL5gkxse7bw212XiMkdzoDWwdvL1EmpYfaMnWVsoq8/nhox14q/J/AvWUeQBZO9OlJ6YZ8fLL1QGrnYEJeRb1KFurbf3Xq8VeD8SueB8imjc8N8bzybWuzBPcSQT0zuD1XdDt0oYHYSP1qh/5D3gwcQAN9vUdi/yVuLbD9WVM70ID+501KxE5VLKjxYeR8EzdN2Bj7us0N5+jNV9wz2X7XbbyCJ02+orppG2U3R0gdi2kbgagfNhk2Q+XqjcxfM8zwZs7P5vUY+rCxL5+XPgnd/fAWCxOeqlbHNaOB9ACTkqX1BQsoHTne9QITutYij6QF2428iT+bs13qleUI4riAWQdjlg+TKihEX/S6JJLrrd6Lzk5fTn+036TeFnQ6oXNgkDdo59V/nepjRWQ1m8T+vF8o3VBLe8kc8BpNNAjdpfM7XjoBD6hMAhE0s+BJaHl1fPqkAV0TEY=
  on:
    repo: eitansuez/articulate
