language: java
jdk:
- oraclejdk8
script: env && ./mvnw package -B
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: esuez@pivotal.io
  password:
    secure: VDb/pV1bSzmTshsWIvuZ0fbPfeLnITxaxZDHhzeNHzBq2HjWbCV8K3StiQ3yLG6oKJjyPVFi46p6e3rPvXbUqQxuhyLmLX11i+McjiCxEPYf/PhwGfgMr9yzRr24qY9fhRCTxGgwmRc6rV6+xwEHJgCiIJaFc9BJH2EudZD+6oeqLR0Li9gM4KARziJxmiFxL0m2Y+eymtMerNvUQv6O5aZ/1dObMW2z6353g6zwCeHl1THCI0ysPXsdB3EIhxbaLlDolyomvhF7dpkocyFHFpQNFCaqsKtbsAFUOcTN3SBAef1q0d4P2OjuNLOcpHjT+CH03Pb1tZRSn5sM4h0HlQb6rXu0D7MJUevDSN8CtDB27OVYoRLEEeW5QNjSQqUJlbRiEynw9zYGqLwbpkRR8ykt+SpeDF42iO93csjqTjWbkDpxVtFbQtOFo7KnNEw/sHFYh+VTKaL0GjAyudcns2X5F4Kz96B2n1sYcU3Su+qvGzZPnjXJyhxNqQKYJn+Z8Q4Xy3H2jlUF8Htm1UBV/8ev79rjNBZZeAhJh+1+M7ip9UuJyKS8CfCVS0DbLhj0mafOxlc8G7p31751yWY0+3vgHr+BZOcLxSZoLTLLpzZqlnAG8MpNhVbzIXmR08KL0SPuoHvUPnMDyS9E1qqs9UWUsPbcyKD8yJZNvannHw8=
  organization: eitan-org
  space: eitan-space
  on:
    repo: eitansuez/articulate
