language: java
jdk:
- oraclejdk8
script: env && ./mvnw package -B
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: esuez@pivotal.io
  password:
    secure: hn0PSzjbZAihgMe6N79SLX4qiqSOANJEWHdbTRti8LE1q2p79jFfiYr7E0BA5+iXaymrhmYONEPPVKLPd9acX+rLlyf3HtZRXvseyX1EIRFu40oZCVYuJxMjSNFsx/+3TjseNdLNtq0sGOh7/dn1hDrFYWRq1IXifEQPIt+gDsgGjtfQAp9f8OY280Gp7wAJM7/6OiFa2NK1XfCRQhaKTdHs3hWWcV1Biz1NvzmIWv64IlaQDPWp6If4sLLMn+4/VegIELonry949hayjCle3vOjqFmJu1I4w3jLi419P8h+hcIjM/nvDfMZF0lD+JEuVt5GFzZhx4nkKGTfUvQm0ELsGMILRQBq84a+GzVs9vxSw8eZZgREqpW1VenJ3PRlJuJj+H//KweP7XxSJApNtuf8cMHvEhXTgfzhrLSNUqIDLHby+c6naJo6JjQ7drh0qS44xoLSkbaC79XRV4uuInff5+li7ZHDKtdu3WfR+AjLJ/aaMzGS1RWrXC4GHAORBtPb12iLIqhkgd3SL17B+R7ujURKJ6Ht7bUCgjyiD7AdPoy98d1G/w0KbIc4qoI3GGLpKJs1H2dTlLzRKiKEXdE/HJuMnB5VLYnENC3KcIEAHzf1IeDk+sOX8vpPqyNAVdyJ79JXFCEZZOmy4HGYyrQ7j3DWgCjtrx04MrKEQas=
  organization: eitan-org
  space: eitan-space
  on:
    repo: eitansuez/articulate
