language: java
jdk:
- oraclejdk8
script: env && ./mvnw package -B
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: esuez@pivotal.io
  password:
    secure: y9RCyts7RNNXl/HfPvtddhDzjR7+uzy+req7ceI8cPnPgghY5qtnqOJef28Qp4PRldxBZjvNpX73Bwf+AI8xbIMjVitZpCi0CMl0pYp1B5ONqxEtimT27IUxRFEtEE6+AcS9BXOrAkz/gh4Uk8D+WbBVoJnlu0b6CabFhdKn9OYQTtS/obc1VYkM1E26+Y83BdWpn1/hCgDZWXAqSpN2g5enCED5A32NS+mbRahmnirltfdsdsCBfsvLs3ywWvWRs5ybrieMKc/ZpRaW9qDXtlAcy5MAvxtitZhp7ShCKm0NGEjxyx9lv6oNsLJTVyKwqPs/6AH2PCWBI6IjXVI/C0eZ8JZ5NokK7UJE6BmexJuV2n6Si6qn8cqZL9LY2CnLJKQfA+Uu8ZvM6WEvpwUBsIPEP49W+PQJeANYOQ8jJQEC9PNOEJp2dNLYsL/bMkE553xZsxQcqHyrYv6VhoIAKuLluLsgRpn1e9Pian+cqYc2iJlCDwK1K3zAnHuGxgGTKxQKba6NcoQ2D5GM1/FnZKgrzaXhorflToCOZoZzGbK6fYkfHdncWJLxvzzJzxqwGfJcXpzy6dkYvgAgjFpiuBaJb5T4xDkeYzc4YAiOqEk3nve0hqKe9Zj81DRikvgl2rX2XwhDrerpFi0lgVVY6o12xv1uUEZNdvqDH4Z//dk=
  organization: eitan-org
  space: eitan-space
  on:
    repo: eitansuez/articulate
